### ISSUE TITLE
Occasional server crash

### ISSUE THREAD

**Issue by Mordenkainen** [TheDrunkMafia/ThaumicInfusion#5]
Server occasionally crashes with the following crash log:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/15/15 4:33 AM
Description: Ticking entity

java.lang.NoSuchFieldError: yLevel
at drunkmafia.thaumicinfusion.common.block.InfusionCoreBlock.func_149719_a(InfusionCoreBlock.java:44)
at net.minecraft.block.Block.func_149731_a(Block.java:712)
at net.minecraft.world.World.func_147447_a(World.java:1221)
at net.minecraft.world.World.func_72933_a(World.java:1024)
at net.minecraft.entity.EntityLivingBase.func_70685_l(EntityLivingBase.java:1906)
at net.minecraft.entity.ai.EntitySenses.func_75522_a(SourceFile:28)
at net.minecraft.entity.ai.EntityAITarget.func_75296_a(SourceFile:101)
at net.minecraft.entity.ai.EntityAINearestAttackableTarget$1.func_82704_a(SourceFile:34)
at net.minecraft.world.chunk.Chunk.func_76618_a(Chunk.java:1001)
at net.minecraft.world.World.func_82733_a(World.java:3229)
at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75250_a(SourceFile:44)
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at drunkmafia.thaumicinfusion.common.block.InfusionCoreBlock.func_149719_a(InfusionCoreBlock.java:44)
at net.minecraft.block.Block.func_149731_a(Block.java:712)
at net.minecraft.world.World.func_147447_a(World.java:1221)
at net.minecraft.world.World.func_72933_a(World.java:1024)
at net.minecraft.entity.EntityLivingBase.func_70685_l(EntityLivingBase.java:1906)
at net.minecraft.entity.ai.EntitySenses.func_75522_a(SourceFile:28)
at net.minecraft.entity.ai.EntityAITarget.func_75296_a(SourceFile:101)
at net.minecraft.entity.ai.EntityAINearestAttackableTarget$1.func_82704_a(SourceFile:34)
at net.minecraft.world.chunk.Chunk.func_76618_a(Chunk.java:1001)
at net.minecraft.world.World.func_82733_a(World.java:3229)
at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75250_a(SourceFile:44)
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
Entity ID: 297
Entity Name: Zombie
Entity's Exact location: 272.06, 64.00, 966.35
Entity's Block location: World: (272,64,966), Chunk: (at 0,4,6 in 17,60; contains blocks 272,0,960 to 287,255,975), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
Level name: world
All players: 1 total; [EntityPlayerMP['Mordenkainen3141'/1167, l='world', x=265.95, y=62.00, z=993.77]]
Chunk stats: ServerChunkCache: 444 Drop: 0
Level seed: 6486103687518005860
Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
Level generator options: 
Level spawn location: World: (230,64,1002), Chunk: (at 6,4,10 in 14,62; contains blocks 224,0,992 to 239,255,1007), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Level time: 12431531 game time, 12766894 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 79085 (now: false), thunder time: 49938 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by TheDrunkMafia** [comment]
Thanks, this should be fixed in the next build.
