### ISSUE TITLE
Spiritus Infusion Crash

### ISSUE THREAD

**Issue by sdaddy** [TheDrunkMafia/ThaumicInfusion#63]
Playing FTB Unstable 1.8.9 on a server and crashed after using the spiritus infusion: http://hastebin.com/raw/vafuruhito

**Comment by TheDrunkMafia** [comment]
When does it crash? On infusion, on block update?

**Comment by sdaddy** [comment]
As soon as I applied it to a block. It was a chisel block that has connected textures. I'm unable to login to the server; it crashes as soon as it begins to load.

**Comment by TheDrunkMafia** [comment]
To fix the issue, go to the config and disable the effect, then delete the TIWorldData folder

**Comment by TheDrunkMafia** [comment]
I'll look into it that effect, however it's one of the effects I was planning on removing since It does not work well with the new system in place.

**Comment by sdaddy** [comment]
The server owner did as you said, but he still had to teleport my player away as it still crashed. I was wrong about when the crash occurred, it's when I tried walking through the blocks. The infusion is still there and if there's blocks placed it'll crash when walking into them. I've removed the blocks and can now walk through without crashing. Seems disabling the infusions after adding them to the world doesn't remove them. Thanks for your help.

**Comment by TheDrunkMafia** [comment]
If the world is now loaded, but the infusion still exists. Then you should be able to run the /cleandata command, which will completely remove all the infusions. Strange that deleting the folder, has not removed the infusion.

**Comment by TheDrunkMafia** [comment]
I've done some debuging (With the same mods as the 1.8.9 pack on a server) and I believe I have found the cause of the issue, It seems to be being caused by how I am detecting super classes in the class writer, during the transformation stage of Minecraft Loading. Would you be able to get the TI_Transformer.log for me, so I can check it against my own.

**Comment by sdaddy** [comment]
Here is mine: http://hastebin.com/raw/ugagutufup If it's the server's you're needing I'll have to contact the server owner tomorrow.

**Comment by TheDrunkMafia** [comment]
Yeah... It was the issue, the block from chisel failed the transformation:
```
==== Block: mod.chiselsandbits.chiseledblock.BlockChiseled has failed injection ==== 
java.lang.IllegalArgumentException: java.io.IOException: Class not found
	at drunkmafia.thaumicinfusion.common.asm.ClassWriterWithoutClassLoading.initializeTypeHierarchyFor(ClassWriterWithoutClassLoading.java:101)
	at drunkmafia.thaumicinfusion.common.asm.ClassWriterWithoutClassLoading.getSuperTypes(ClassWriterWithoutClassLoading.java:70)
	at drunkmafia.thaumicinfusion.common.asm.ClassWriterWithoutClassLoading.getCommonSuperClass(ClassWriterWithoutClassLoading.java:37)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
	at drunkmafia.thaumicinfusion.common.asm.BlockTransformer.transform(BlockTransformer.java:280)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mod.chiselsandbits.registry.ModItems.<init>(ModItems.java:61)
	at mod.chiselsandbits.core.ChiselsAndBits.preinit(ChiselsAndBits.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at drunkmafia.thaumicinfusion.common.asm.ClassWriterWithoutClassLoading.initializeTypeHierarchyFor(ClassWriterWithoutClassLoading.java:77)
	... 53 more
```

**Comment by TheDrunkMafia** [comment]
I've fixed the issue, I will be releasing it in the next update and hopefully FTB will update the pack with it in. The update should hopefully be out by the end of tomorrow, I want to include some changes to existing effects to make them more interesting and spiritus will be one of them, since it does not even work well with the current system in place.

**Comment by TheDrunkMafia** [comment]
I've released the new version with the fixes for the spirtus infusion and the mod compatability issues, all should be working now. As I have tested it in the unstable pack and with the chisel blocks.

**Comment by sdaddy** [comment]
Thanks so much. Really enjoy the mod. :smile:
